name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Atau branch yang Anda gunakan

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Tambahkan langkah untuk menjalankan skrip build
    - name: Run build script
      run: npm run build  # Sesuaikan perintah ini dengan skrip build Anda

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MUTASIDANA_CAB3B }}
